### ISSUE TITLE
Add discrete GPU pass-through

### ISSUE THREAD

**Issue by flexiondotorg** [quickemu-project/quickemu#133]
Add support for PCIe GPU pass-through.

**Comment by Rukurn** [comment]
I don't use Windows apart from gaming virtual machines, so to be able to quickly set up a VM so I can play a game with my friends and then delete it would be incredible.

Thank you for all the hard work you do on this project.

**Comment by takov751** [comment]
My proposal is that there should be a new script something name like `quickpass`, which would help the user to modify the conf file after install to make proper pass-trough happens. This  could mean to map out iommo groups, advice user which gpu and pcie device to isolate (usb hub, networkcard, soundcard).

PS: This script should have a `quickpass check` function to determinate if hardware is capable of isolation at all. To inform the user beforehand so that they wouldn't try to debug and spend hours why it's not working.

**Comment by kevindurb** [comment]
A while ago I started working on something similar. It has a bunch of logic in it already for many of the checks for gpu passthrough. Feel free to take ideas from it!

https://github.com/kevindurb/gpu-passthrough-helper

**Comment by zen0bit** [comment]
Or here lot of helpers:
@pavolesig

I made one for void from it...

**Comment by osevan** [comment]
https://github.com/NextWork123/VFIO-KVM

**Comment by flexiondotorg** [comment]
Duplicate of #688

**Comment by beedell-roke** [comment]
@flexiondotorg, that's more of a discussion on how to achieve it. Even if this issue were locked, I'd still appreciate a way to track its implementation.
