### ISSUE TITLE
Document quickemu conf file

### ISSUE THREAD

**Issue by zenmaster24** [quickemu-project/quickemu#251]
#### Expected behaviour

This is a question around usage - I'd like to know what options i can put in the conf file, and their syntax

#### Actual behaviour

I cant find this documented anywhere

#### Steps to reproduce the behaviour

`quickemu -h` outputs ` Usage quickemu --vm ubuntu.conf` which is not helpful

#### Quickemu output

```
$ quickemu --version
2.3.2
$ quickemu -h       

Usage
  quickemu --vm ubuntu.conf

You can also pass optional parameters
  --delete                : Delete the disk image.
  --display               : Select display backend. 'sdl' (default), 'gtk', 'none', or 'spice'
  --fullscreen            : Starts VM in full screen mode (Ctl+Alt+f to exit)
  --ignore-msrs-always    : Configure KVM to always ignore unhandled machine-specific registers
  --screen <screen>       : Use specified screen to determine the window size.
  --shortcut              : Create a desktop shortcut
  --snapshot apply <tag>  : Apply/restore a snapshot.
  --snapshot create <tag> : Create a snapshot.
  --snapshot delete <tag> : Delete a snapshot.
  --snapshot info         : Show disk/snapshot info.
  --status-quo            : Do not commit any changes to disk/snapshot.
  --version               : Print version
```

#### Linux Distribution & Kernel

```bash
$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

$ uname -a
Linux $HOST 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by philclifford** [comment]
Thanks for your feedback.

The script sets the following variable defaults and then reads the overrides that `quickget` or the user has written into the config file.

```
# Lowercase variables are used in the VM config file only
boot="efi"
bridge=""
cpu_cores=""
disk_img=""
disk_size=""
fixed_iso=""
floppy=""
guest_os="linux"
img=""
iso=""
macos_release=""
port_forwards=()
preallocation="off"
ram=""
secureboot="off"
tpm="off"
usb_devices=()
```
`quickget`will have written sensible workable defaults and requirements.  Since there is already an issue requesting man pages, perhaps someone will write one for the config as well.  For now all of the above options are documented in the README.md (either where they are specifically relevant to e.g. MacOS or Windows, or in the later sections. Hopefully you can find everything you need there until someone contributes a man page.  If you find there is anything unclear or omitted from the README.md please add it here.

**Comment by ItzSwirlz** [comment]
Documentation would be good aswell for packagers. I'd love to package this for Debian (as a .deb) and for RPMs

**Comment by philclifford** [comment]
Anything to add to/change from the generated man page and markdown [here](https://github.com/philclifford/quickemu/blob/add-man-pages/docs/quickemu_conf.1.md) ?

**Comment by flexiondotorg** [comment]
The configuration file is documented here: https://github.com/quickemu-project/quickemu/blob/master/docs/quickemu_conf.1.md
