### ISSUE TITLE
Can Windows virtual machines be used for gaming on Linux hosts?

### ISSUE THREAD

**Issue by trymeouteh** [quickemu-project/quickemu#273]
If you a poweful computer, could one use Quickemu to have a Windows 10 virtual machine and use it for gaming or are there unforeseen issues when doing this?

**Comment by takov751** [comment]
For that you would need gpu passtrough , which is still not implemented and ideally two gpu and would descent motherboard with the needed iommu groups, there's a chance that most basic (gaming) desktop setup  might not have .

**Comment by kekonn** [comment]
I think building upon [Looking Glass](https://github.com/gnif/LookingGlass) would help a lot

**Comment by takov751** [comment]
It is on The road map, however doing these things are really hardware specific and lots of space for error. And writing checks and automation for it is demanding. More complicated to implementthen the whole quickemu project functions on its own all together . In my opinion . Because most of the device is not capable of for example gpu passtrough

**Comment by flexiondotorg** [comment]
Yes VMs can be used for gaming, but Quickemu really needs GPU passthrough support before it is viable.
