### ISSUE TITLE
Document How To use Spice with bridge networking

### ISSUE THREAD

**Issue by SprickW** [quickemu-project/quickemu#297]
#### Expected behaviour

I expected the VM to come up normally, just exchanging NAT IP by bridge IP

#### Actual behaviour

When adding the bridge="br0" line to the conf file, when trying to start VM immediately a "Connect to SPICE" window pops up asking for Hostname, Port, TLS Port and showing recent connections that obviously now don't work anymore.

As don't know much about spice, maybe just some more lines in the docs might help.

#### Steps to reproduce the behaviour

Add bridge line to conf file.

#### Quickemu output

n/a

#### Linux Distribution & Kernel

$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

$ uname -a
Linux xxxxxx 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ChrisMacGregor** [comment]
I think this is because qemu fails to start up, but that is not detected by quickemu, and then spicy is started by quickemu but can't find anything to connect to (because qemu bailed out with an error), so it prompts you.

On Ubuntu 21.10, I fixed this by following advice I found in a bunch of googling:

```
sudo mkdir /etc/qemu
echo allow br0 | sudo tee /etc/qemu/bridge.conf
sudo chmod u+s /usr/lib/qemu/qemu-bridge-helper
```

Not sure if it's the *right* fix, and in particular I'm uncomfortable with the "fix" being to make something setuid that isn't already.  But this got qemu to start up, at least.  I'm still trying to get the bridge to actually work properly...

I also did this, though I'm not sure if it made a difference or not:

`sudo addgroup $USER netdev`

(and then for it to take effect, you'd have to either log out and back in, or use "newgrp netdev" and then "newgrp $USER").

**Comment by flexiondotorg** [comment]
@ChrisMacGregor Please see my request for documentation improvement in #287

**Comment by ChrisMacGregor** [comment]
> @ChrisMacGregor Please see my request for documentation improvement in #287

Okay, thanks.  I never did get it to actually work, and after wasting at least day trying, since I had an adequate workaround (to just specify a fixed port number for Spice to map for ssh for each VM) I couldn't justify spending more time on it.
