### ISSUE TITLE
how i can disable internet acces of vm?

### ISSUE THREAD

**Issue by osevan** [quickemu-project/quickemu#419]
I need only localhost connection.

But when I want internet connection etc....

After restart and editing config

His I can do that?

**Comment by philclifford** [comment]
Either use firewall/routing on your host/route to block outbound from the VM or set `-nic none` in the generated <vm>/<vm>.sh (or a copy since that will be re-generated if you run quickemu).

Depends what you want to do/achieve. You might want to look at https://wiki.qemu.org/Documentation/Networking

**Comment by osevan** [comment]
Where is generated sh located?

**Comment by flexiondotorg** [comment]
Kind of a duplicate of #478. Configuring a VM to have no network seems reasonable to me.
