### ISSUE TITLE
Setting display= in the VM configuration is no longer honoured

### ISSUE THREAD

**Issue by nicolasmol** [quickemu-project/quickemu#520]
Hi
From your recent update (less thant a few days).
Under Linux mint.
I was before this update using Gtk display and there was a "menu bar" which has disappeared (the same for spice).
Then I was able to move the application window on second monitor and toggle full-screen (ALT+CTRL+F). At this time, it was possible to move the mouse cursor over the two monitors.
Since your recent update, toggling full screen (gtk) keeps the mouse grabbed only by the application window. ALT+CTRL+G does nothing. So i'm not able anymore to move the cursor over the two monitors.
Rolling back to previous /bin/quickemu does fix it.

**Comment by flexiondotorg** [comment]
I can not reproduce this.

**Comment by nicolasmol** [comment]
Sorry I was on something else for a while.
I just tried on 4.2 it's the same result. Watch in this video the difference between 3.15 & 4.2

[cinnamon-20220919-10.webm](https://user-images.githubusercontent.com/61077647/191062098-0e2ccf54-d469-4a1f-adf3-5257a2fac589.webm)

**Comment by nicolasmol** [comment]
But it seems you removed gtk ?

**Comment by flexiondotorg** [comment]
Thanks for the feedback.

A recent commit accidentally removed applying `display=` VM configuration options: https://github.com/quickemu-project/quickemu/commit/e8b1b7cb3e43f71e605cee7f68f7f19990cee149

This was a mistake and is a bug. It will be fixed in the next release of Quickemu.

In the meantime, the following workaround is available; add `--display gtk` when you launch a VM with `quickemu`
