### ISSUE TITLE
SPICE installation location not clear

### ISSUE THREAD

**Issue by oldcastlehq** [quickemu-project/quickemu#539]
Hi,

The documentation is not clear on this part:

``` bash
quickget ubuntu 22.04
quickemu --vm ubuntu-22.04.conf
```

-   Complete the installation as normal.
-   Post-install:
    -   Install the SPICE agent (`spice-vdagent`) to enable copy/paste
        and USB redirection
        -   `sudo apt install spice-vdagent`
    -   Install the SPICE WebDAV agent (`spice-webdavd`) to enable file
        sharing.
        -   `sudo apt install spice-webdavd`

Where do I install SPICE? On the host or the guest?

**Comment by philclifford** [comment]
On the guest.  The documentation could be more explicit, but may perhaps be forgiven since in context you are installing the guest OS, then "post-install" installing the SPICE Agent ... which is a clearly confusion shortening of  [Spice guest agent X11 session agent](
https://manpages.ubuntu.com/manpages/trusty/man1/spice-vdagent.1.html)

Sorry for the confusion - I'll try and sneak some more explicit wording into the next release.
