### ISSUE TITLE
ISO url issues with multiple distros

### ISSUE THREAD

**Issue by takov751** [quickemu-project/quickemu#557]
#### Actual behaviour
URLs of
 
- debian 11.4
- deeping
- devuan(filename 4.0.2 instead 4.0.0)
- kolibrios(invalid website certificate)
- mxlinux 21.1
- reactos error in url generation ```curl https://sourceforge.net/projects/reactos/files/latest/download -L -s --head|tac| grep location|cut -d " " -f 2|head -n1``` possible solution
- regolith #551 
- rockylinux 8.4 (string dvd1 on website while dvd in url)

#### Steps to reproduce the behaviour

I am working on the #398  again, still need debugging especially since ubuntu in quickget broke my function.
have some interesting findings

**Comment by philclifford** [comment]
Hi @takov751 .  I had a few pending PRs from using my slightly-mashed and de-broken(mostly) version of an old version of your 398 branch to check the links, and which got merged.  Still has some breakages and false-positives but was able to spot a few of the above, hence the PRs.  Also I have a pending one to dynamically detect new debian releases so their behaviour doesn't break us at every point release. That's why Martin only had a couple left to fix to close this.

Hopefully kolibrios will get their cert sorted soon. Can't say I disagree with dropping regolith (at least for now). 

Will try and catch up with you about 398 as I still find that work very useful!
