### ISSUE TITLE
Install quickemu on Debian 11 Kde plasma

### ISSUE THREAD

**Issue by akelmj** [quickemu-project/quickemu#583]
Hi,

How to install On Debian 11?

I get some errors when install :

`sudo apt install qemu bash coreutils ovmf grep jq lsb procps python3 genisoimage usbutils util-linux sed spice-client-gtk swtpm wget xdg-user-dirs zsync unzip
`

I get errors on **lsb** and **swtpm**

also add reposetory :

`sudo apt-add-repository ppa:flexiondotorg/quickemu`

show errors on debian 11.

any idea please?

**Comment by planceleur** [comment]
Exactly the same problem here. I replaced lsb with lsb-base and swtpm with libtss2-tcti-swtpm0 to avoid requirements error. Unfortunately there is no way to test if this is enough as the second part of installation fails as akelmj explains.

I tried any workaround I could find googling quiet intensively.
Always end up with this error:
"E: Impossible de récupérer http://ppa.launchpad.net/flexiondotorg/quickemu/ubuntu/dists/lunar/main/binary-amd64/Packages  **404  Not Found [IP : 185.125.190.52 80]**"
Note the 404 issue. 

Works like a charm on Ubuntu or POP!OS.

Thanks for your work btw. I built a portable external SSD with all releases I needs, and use it on my host machines, except Debian 11 so far...

**Comment by planceleur** [comment]
Hi, found a workaround to this question: use quickemu with nix.
Procedure:
- install nix (mulit-user mode is ok)
`sh <(curl -L https://nixos.org/nix/install) --daemon`
There were two required pachages not already installed on my machine: `sudo apt install curl xz`
- start quickemu in a nix-shell for instance
nix-shell -p quickemu
- Then, start using quickemu commands
- For instance, go to your qemu folder and start a vm(in my example I am using an external SSD mounted on /media/specificuser/qemu - where "specificuser" is your user session. Also note that I have to use "--display spice" as the default display sdl does not work):
`[nix-shell:/media/regularuser/qemu/qemufiles]$ quickemu --vm kali-current.conf --display spice`

Hope this help...
Philippe

**Comment by akelmj** [comment]
Hi,

I success to run quickget using git clone  ([see this link](https://github.com/quickemu-project/quickemu#other-linux)):

`git clone --filter=blob:none https://github.com/wimpysworld/quickemu
cd quickemu`

Then run this command to get alpine latest version:

'
sudo bash ./quickget alpine latest
'

**Comment by eliminmax** [comment]
I was able to install on Bullseye with a few extra steps.
1. Enable the official [Debian Backports Repository](https://backports.debian.org/Instructions/)
2. Manually install the `qemu-system` package from the `bullseye-backports` apt repository (`apt install qemu-system --target-release bullseye-backports`)
3. Install other listed dependencies, replacing `lsb` with `lsb-release`
4. Download the latest release from this repo on Github.

<details><summary>a (slightly) cleaner way</summary>
<p>I'm working on a collection of empty dependency-only "Metapackages", primarily for personal use on my Debian-family systems, so that if I install dependencies for something I no longer want or need, I can uninstall the dependency metapackage. I've made a `quickemu-deps` metapackage for Quickemu 4.6's dependencies, available for download on my debian-dependency-metapackages repo's Release page.</p><p><a href="/eliminmax/debian-dependency-metapackages/releases/tag/v2">Link to the release</a><br><a href="/eliminmax/debian-dependency-metapackages/">Link to the Github repo</a></p>
<p>This essentially combines steps 2 and 3 of the above process, and makes them easier to undo if you later decide to uninstall Quickemu. You still need to enable backports, and manually install Quickemu.</p>
<p>I'm keeping this in a <code>&lt;details&gt;</code> block to avoid cluttering this issue with what could be easily characterized as promoting a mostly-unrelated personal project.</p>
</details>
