### ISSUE TITLE
Windows 10 & 11 Download URL not leading to Microsoft CDN

### ISSUE THREAD

**Issue by sanshibu** [quickemu-project/quickemu#612]
#### Expected behaviour

I was downloading windows 10 & 11 using quickget and it shows the error.

#### Actual behaviour

When downloading windows 11 & 10 using quickget, it shows error

#### Steps to reproduce the behaviour

Outline the step to reproduce the issue you've encountered.

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.
./quickget windows 10
Getting Windows 10 URL...
Download URL not leading to Microsoft CDN

./quickget windows 11
Getting Windows 11 URL...
Download URL not leading to Microsoft CDN

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```
lsb_release --all
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 37 (Thirty Seven)
Release:	37
Codename:	ThirtySeven

uname -a
Linux fedora 6.0.18-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 7 17:10:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by antonc42** [comment]
I'm also having this issue on Kubuntu 22.04. I installed from the PPA.
```
quickget windows 10
Getting Windows 10 URL...
Download URL not leading to Microsoft CDN
```


```
lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
```
uname -a
Linux nightmarechild 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
quickemu --version
4.5
```

**Comment by antonc42** [comment]
After a bit more investigation, it appears that there is some problem with either the third party site being used to get the Windows ISO download link (https://tb.rg-adguard.net) or possibly with the Microsoft download URL. I get a 403 Forbidden error when the third party site redirects to the Microsoft URL.

**Comment by chukfinley** [comment]
I'm also having this issue on Arch Linux, they should make their ow ISO mirror

**Comment by poetislands** [comment]
Same problem. Also Ubuntu 22.04.1 LTS

**Comment by pachothun18** [comment]
same here,arch,i even try different country proxy,no change

**Comment by Luk45135** [comment]
(https://tb.rg-adguard.net/) Doesn't work anymore for Windows ISOs, but
(https://files.rg-adguard.net/) does.

**Comment by dylanvdmerwe** [comment]
Any luck on this? Probably just an incorrect URL somewhere.

**Comment by mr-sihc** [comment]
any way to do it manually, and still have it work, just specifying the dowloaded path anywhere?

**Comment by nhasian** [comment]
I was looking forward to trying out Quickemu on my fresh install of Ubuntu 22.10 but I'm running into the same problem. 

```
Getting Windows 11 URL...
Download URL not leading to Microsoft CDN
```

**Comment by takov751** [comment]
I have debugged manually the process and it seems tb.rg-adguard has issues fetching download link,which causing this issue.
It would be worth to investigate instead https://github.com/uup-dump further. however their json api is dead. or at least https://api.uupdump.net leads nowhere(missing A record in dns)

**Comment by msmafra** [comment]
Don't know if this helps: 
The Windows ISO download page is generating a download URL with expiration date the 'e' variable is an UNIX Epoch date and time integer with +24 hours from the time you generated the download link, but matching t and h are also needed for it to work. So trying what I did setting the 'e' var value to a later date and time, won't work. https://software.download.prss.microsoft.com/dbazure/Win11_22H2_BrazilianPortuguese_x64v1.iso?t=0d0cb8f8-7226-4a87-ad90-8584eca1b737&e=1675014358&h=93259eb6880a6a166e577975a5629adbed2c062b5d45d3f7210fa1ba3de78ce0

[Guessing mode here] 
They are probably doing it because to block 3rd party scripts and programs (Windows ISO Downloader, for example) used to download their ISO's directly. Maybe considering it a potential security risk (???). Who knows!  I don't have a way to test Windows ISO Downloader, which I used a lot at my Windows days, because sent my machine for warranty repairs and my "backup" one is from 2012 :).

**Comment by takov751** [comment]
@msmafra indeed. Thats the reason these few api still there as there more hoops to jump than just to edit expire date. And whats makes it more difficult is quickemu "bashism" approach which means we have stay close to bash only solutions as we can. Which is why we might have to think about writing or hosting an api ourselfs

**Comment by takov751** [comment]
Another findings. Perhaps we could use https://opendirectory.luzea.de/GezoeSloog/OS/NT10/ as an alternative way to download windows 10 and 11, but the source is of course not official

**Comment by msmafra** [comment]
Considering this PowerShell  script https://github.com/pbatard/Fido, it seems not viable to try via bash + curl

**Comment by takov751** [comment]
> Considering this PowerShell  script https://github.com/pbatard/Fido, it seems not viable to try via bash + curl

Indeed it would need to be a separated script which would be possibly not bash.

**Comment by rubinlinux** [comment]
If you just need to get up and running today (before the script is fixed) with windows 10:

go to https://www.microsoft.com/en-us/software-download/windows10ISO and download the iso to your home directory. Then make a copy of /usr/bin/qemuget in your home directory:

    cp -a /usr/bin/qemuget ~/myqemuget

 and edit it with your fav text editor; change the windows_get() function ( around line 1880):

comment out 

    #if [[ ! ${DOWNLOAD_URL} =~ ^${MS_BASE_URL} ]]; then
    #    echo "Download URL not leading to Microsoft CDN"
    #    exit 1
    #fi

    #echo "Downloading ${WINDOWS_NAME}..."
    #web_get "${DOWNLOAD_URL}" "${VM_PATH}" "${FILE_NAME}"

and under it add:

    echo "Copying ${WINDOWS_NAME} from downloads"
    cp ~/Downloads/Win10_22H2_English_x64.iso "${VM_PATH}/${FILE_NAME}"


where the path to the .iso is whatever you saved it as.

Then you can run 

    ./myqemuget windows 10
