### ISSUE TITLE
Windows download via wget extremely slow but works fine in browser

### ISSUE THREAD

**Issue by tbaumann** [quickemu-project/quickemu#898]
I'm not sure this has anything to do with quickget. But Apparently I'm not the first this happens to

#### Expected behaviour

```bash
 
› quickget windows 10
Downloading Windows 10...
 - Product edition ID: 2618
 - SKU ID: 16067
 - Got latest ISO download link (valid for 24 hours): https://software.download.prss.microsoft.com/dbazure/Win10_22H2_English_x64v1.iso?t=438bb5d1-921e-4a1c-a50e-c63f2c65358e&e=1704279960&h=58aef4b7605ef871d4d5c1fb0cd651c038a77d9635ab95a66634b64949580b53
windows-10/Win10_22H2_English_x64v1.iso                                1%[=>                                                                                                                                                                  ]  80.86M   167KB/s    eta 6h 20m 
```
Never more than 250kb/s!

#### Actual behaviour

Full speed download

#### Steps to reproduce the behaviour

When I launch that command again or use the link in a browser I get full speed.
```
 wget --quiet --continue --tries=3 --read-timeout=10 --show-progress --progress=bar:force:noscroll https://software.download.prss.microsoft.com/dbazure/Win10_22H2_English_x64v1.iso?t=438bb5d1-921e-4a1c-a50e-c63f2c65358e&e=1704279960&h=58aef4b7605ef871d4d5c1fb0cd651c038a77d9635ab95a66634b64949580b53 -O windows-10/Win10_22H2_English_x64v1.iso
```

#### Linux Distribution & Kernel

```bash
Distributor ID:	NixOS
Description:	NixOS 24.05 (Uakari)
Release:	24.05
Codename:	uakari
Linux zuse 6.6.7 #1-NixOS SMP PREEMPT_DYNAMIC Wed Dec 13 17:45:36 UTC 2023 x86_64 GNU/Linux
```

**Comment by TuxVinyards** [comment]
Quite a few things to note here.

You should aria2 installed.  Quickemu uses aria2, where possible.  If you were using qqX, you would have had a pop up to tell you this.

If you have tested the Microsoft servers correctly, before putting up this post, ie on different days, different times of day, after rebooting your router and switching your IP address, then the problem is most likely that your ISP is profiling and filtering your traffic.

If you are using a standard ISP provided router you are advised to switch to your own, one they that are not able to remotely control.  You should also change to your DNS settings so they point away from your ISP.  Use Cloudflare (1.1.1.1) as primary and Google (8.8.8.8) as secondary.  Or vice versa depending on how they ping ...

This problem is not reproducible.  Either you haven't tested sufficiently or it's your router/ISP.  Even wget shouldn't run this slow.

See this screenshot from morning, when I was testing qqX pre-release.   Windows 10 was a 60 sec download on Gigabit fiber. 


![Screenshot at 2024-01-03 07-54-09](https://github.com/quickemu-project/quickemu/assets/3956806/a648751e-e116-476a-a04b-6788b4c999c6)

**Comment by tbaumann** [comment]
Yes I actually don't think that's got anything to do with the way wget is used.
Something must have upset the CDN. I'm using in Morocco, peering is always a bit rough from here.

My first intuition was some kind of punitive throttling based on user agent or so. But that actually very unlikely and doesn't explain why the next request works just fine.

Sorry to bother. Closing

**Comment by TuxVinyards** [comment]
I had to test qqX anyway .... 👍
