### ISSUE TITLE
quickemu create VM error when use 1T RAM

### ISSUE THREAD

**Issue by i-moxi** [quickemu-project/quickemu#899]
![image](https://github.com/quickemu-project/quickemu/assets/88470026/1aaa336a-a4d1-49a8-8923-cdd2d5753817)

![image](https://github.com/quickemu-project/quickemu/assets/88470026/ae89270f-5959-4735-8a9a-c60a43133334)

I think it looks better use `free -g` directly but not use 'free -h' then grep it

temp fix: /usr/bin/quickemu
```
  local RAM_VM="4G"
    # if [ -z "${ram}" ]; then
    #     local RAM_HOST=""
    #     RAM_HOST=$(free --mega -h | grep Mem | cut -d':' -f2 | cut -d'G' -f1 | sed 's/ //g')
    #     #Round up - https://github.com/wimpysworld/quickemu/issues/11
    #     RAM_HOST=$(printf '%.*f\n' 0 "${RAM_HOST}")
    #     if [ "${RAM_HOST}" -ge 128 ]; then
    #         RAM_VM="32G"
    #     elif [ "${RAM_HOST}" -ge 64 ]; then
    #         RAM_VM="16G"
    #     elif [ "${RAM_HOST}" -ge 16 ]; then
    #         RAM_VM="8G"
    #     elif [ "${RAM_HOST}" -ge 8 ]; then
    #         RAM_VM="4G"
    #     fi
    # else
    #     RAM_VM="${ram}"
    # fi
    echo ", ${RAM_VM} RAM"
```

**Comment by TuxVinyards** [comment]
This is quite an interesting conundrum.

The quickemu calcs are very simplistic, which is why I wrote the qqX tune-up routine.  At outlier RAM quotas you should definitely be specifying ram in the  .conf file .  Not much good if quickemu throws up its arm in horror though :rofl:

A lot of the user base for quickemu have only 8G of RAM.   I use 16, which for me is more than adequate.   Gamers might have 32.  Some might have 64.   I don't think a Terabyte was ever imagined ... 

Using '-g' won't work for the main user base as the rounding is too crude.   A better solution might  '-m'  or  grepping for the 'T' output.  

The solution I went for in qqX  was to use  '--mega -h'  and was probably only because I was following what was done in quickemu.   There may have been another reason but I don't remember.  I do remember that it was a lot of messing around.  But that could have been because I had been following the '--mega -h' route. :rofl:

The quick fix would be to grep for 'T'  then run this to an exception that checks for a .conf value and errors if one is not present.

Personally, I think I might revisit  the qqX routine and play around with the '-m' output.  When I have time.  I found the following note in my code `# @2023/11 free --mega  can fail in Manjaro ( & arch ?) at the command prompt at least  (interactive)`  which is another reason.

![Screenshot at 2024-01-05 10-51-36](https://github.com/quickemu-project/quickemu/assets/3956806/21742659-661f-4093-9626-ddbc86f1d418)

**Comment by lj3954** [comment]
> This is quite an interesting conundrum.
> 
> The quickemu calcs are very simplistic, which is why I wrote the qqX tune-up routine. At outlier RAM quotas you should definitely be specifying ram in the .conf file . Not much good if quickemu just throws up its arms in horror though, if you haven't 🤣
> 
> A lot of the user base for quickemu have only 8G of RAM. I use 16, which for me is more than adequate. Gamers might have 32. Some might have 64. I don't think a Terabyte was ever imagined ...
> 
> Using '-g' won't work for the main user base as the rounding is too crude. A better solution might be '-m' or grepping for the 'T' output.
> 
> The solution I went for in qqX was to use '--mega -h' and was probably only because I was following what was done in quickemu. There may have been another reason but I don't remember. I do remember that it was a lot of messing around. But that could have been because I had been following the '--mega -h' route. 🤣
> 
> Quickemu only does the calcs if a .conf value is not present. The quick fix would be to grep for 'T' then handle this as an exception error informing the user to edit the .conf.
> 
> Personally, I think I might revisit the qqX routine and play around with the '-m' output. When I have time. I found the following note in my code `# @2023/11 free --mega can fail in Manjaro ( & arch ?) at the command prompt at least (interactive)` which is another reason.
> 
> ![Screenshot at 2024-01-05 10-51-36](https://private-user-images.githubusercontent.com/3956806/294459003-21742659-661f-4093-9626-ddbc86f1d418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTE4NzUsIm5iZiI6MTcwNDY5MTU3NSwicGF0aCI6Ii8zOTU2ODA2LzI5NDQ1OTAwMy0yMTc0MjY1OS02NjFmLTQwOTMtOTYyNi1kZGJjODZmMWQ0MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDUyNjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTg4YjZjYWFiYjZlZmNkZDRmZTY2MTgzMDBhZWY2MjAyZDZhOGIwMTMxZjQ4NjY0NDk2NjJlZDVjOTBjNDExNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V80Zk0x4dkAjvGG1TDfTxFiSD5qHWmaSRy9ueCeM5kU)

This is not an issue with any calculation. It's how the number is filtered out of the text that's the problem. `cut -d'G' -f1` prints out everything preceding the first capital G, which in a system with anywhere between 1 and 999GB of RAM, will print out a number. If there's any larger or smaller amount of RAM (in megabytes, terabytes, or any other unit), it'll print out the amount of RAM in terabytes or whatever unit, **followed by the letter**, and then any other numbers that come before the next letter G. I created a variable with output from `free --mega -h` but edited my actual RAM amount to '5T', and the output after formatting is "5T8.0", since 8.0 is followed by "G". Obviously, this is not a number and cannot be rounded to anything.

I believe the best solution would be to use the free command by itself, which prints out an amount of RAM in bytes, and extract the first number (which is the total amount of RAM) by itself. This should do the job perfectly.
```free | tr ' ' '\n' | grep -m 1 [0-9]```

**Comment by TuxVinyards** [comment]
@lj3954  your solution looks better than my musings with alpha filtering that Github  managed to auto-attach to this issue.

I quite like what you have done.   I found that this variant seems to work quite well for shared memory too.  `free --mega | tr ' ' '\n' | grep -m 4 [0-9] | tail -1`   A lot of users have less RAM due to integrated graphics.  This is not an issue that is addressed in quickemu so technically out of the scope of your PR.  But  I though worth mentioning FWIW.

I can't replicate your tests for '5T' .   What method did you use?    Looking at the OP  screenshot  I can see, following your notes,  how  the  cut at  'G'  creates an output of  '1.0T43'.    Does `free  --giga `  not output with a 'T' ?

@i-moxi  What does a screenshot of  genuine `free --giga` look like on your machine?

**Comment by TuxVinyards** [comment]
@i-moxi  Thanks for quick reply.    Looks like we have a good working solution then. :+1:
