### ISSUE TITLE
No disk found when installing windows 11 Pro

### ISSUE THREAD

**Issue by pcace** [quickemu-project/quickemu#927]
#### Expected behaviour

Windows 11 installs

#### Actual behaviour

i get into the windows setup, but there is no disk selectable in setup.

#### Steps to reproduce the behaviour

- create a config: 
```
guest_os="windows"
disk_img="windows-11/disk.qcow2"
iso="Win11_23H2_German_x64v2.iso"
fixed_iso="virtio-win-0.1.240.iso"
tpm="on"
secureboot="off"
cpu_cores="6"
ram="16G"
disk_size="300G"

```
 --> quickemu --vm windows-11.conf

![image](https://github.com/quickemu-project/quickemu/assets/1011875/923ea87f-77e8-4dca-aff6-2ed3931c863d)

#### Quickemu output

```
Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v7.0.0
 - Host:     Pop!_OS 22.04 LTS running Linux 6.6 (hannes-lnx)
 - CPU:       11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
 - CPU VM:   1 Socket(s), 3 Core(s), 2 Thread(s), 16G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/OVMF/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-11/disk.qcow2 (300G)
             Looks unused, booting from Win11_23H2_German_x64v2.iso
 - Boot ISO: Win11_23H2_German_x64v2.iso
 - CD-ROM:   virtio-win-0.1.240.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - TPM:      windows-11/windows-11.swtpm-sock (14684)
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-11/windows-11-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-monitor.socket
 - Serial:   On host:  nc -U "windows-11/windows-11-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-serial.socket
 - Process:  Starting windows-11.conf as windows-11 (14697)
 - Sending:  sendkey ret
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```
```
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```
`Linux user-lnx 6.6.10-76060610-generic #202401051437~1704728131~22.04~24d69e2 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux
`

If anyone has an idea what to do i would be very happy!! THanks a lot for help!

**Comment by pcace** [comment]
Quick reply - when installing it with quickget it works. but i have to manually replace the iso path in the config

**Comment by pcace** [comment]
Why is this closed? The problem persists.

**Comment by ddcampayo** [comment]
Hi,

I just run into the same problem, but I added a second CDRROM device with the  virtio-win image, and upon clicking "Load controllers", I was given some options. For Windows 11, the obvious one was E:\amd64\viostor\w11\viostor.inf. The hard drive was then found. I took all this from  [Virt-manager from Manjaro](https://wiki.manjaro.org/index.php/Virt-manager#Install_virt-manager.2C_qemu_and_all_dependencies)

**Comment by jeancf** [comment]
I confirm that I also experienced the issue and I had to manually select the driver `E:\amd64\viostor\w11\viostor.inf` to make the drive appear.

**Comment by mathgeniuszach** [comment]
Why was this closed? It's a legitimate issue someone is having. At the very minimum, could you at least provide information as to _why_ this problem is invalid?

**Comment by navjotjsingh** [comment]
The issue is still there. Please reopen it. @flexiondotorg

**Comment by kalyanoliveira** [comment]
my knowledge about the below is poor, so bare with me if I do not get the specifics correct

as far as I understand, when you cannot find disks to install windows to, you likely have a failed installation of virtio drivers:

<img width="801" height="365" alt="Image" src="https://github.com/user-attachments/assets/53588857-9914-48fd-acaf-6ac462ead0d4" />

the thing is, when you run the `$ quickget windows 11` command, you get the `virtio-win.iso` file, which (I think?) are your virtio drivers

the problem is that the installation of those drivers often fails

this issue (still open as Im typing this) talks about this: https://github.com/quickemu-project/quickemu/issues/1475

quickemu fails to properly install the virtio drivers (for reasons that are explained in that issue's thread, go read if you're curious, but what matters is that it fails - quickemu has a bug somewhere in its codebase, and that's why it fails), and you get an error such as `windows installation encountered an unexpected error. Error code 0x80070103 - 0x40031`

you can straight up just not try to install those virtio drivers by uncommenting the `fixed_iso="windows-11/virtio-win.iso"` line from your `windows-11.conf` file, but then, of course, you end up with "no disk selectable in setup." this (or something similar) is likely what the OP of this issue is experiencing

however, people in the community have come up with workarounds for the fact that quickemu fails to install those virtio drivers correctly. they are discussed in that issue that I linked, #1475

either you 

1. run the script provided in https://github.com/quickemu-project/quickemu/issues/1475#issuecomment-2727231076 to "fix" your virtio-win.iso file (YOU MUST ADJUST `VM_PATH` BEFORE RUNNING), or you 

2. follow the steps listed in here https://github.com/quickemu-project/quickemu/issues/1475#issuecomment-2784901936 (and here https://github.com/quickemu-project/quickemu/issues/1475#issuecomment-3343178506)

today I used solution 1, and I was able to run a windows 11 vm. have not tried solution 2 (because I have no idea how to rebuild unattended.iso), but I would assume that it also works

also worth mentioning pr #1745 , which is supposed to fix all of these virtio issues based on the findings of #1475 . but it was literally opened 4 days ago, so it'll probably take a while to kick in.

also since the PR mentions that it fixes installation for a specific version of windows, maybe a downgrade could work? idk tho

**Comment by Falderian** [comment]
Just found a temporary "fix", switch the guest os before install, and after you can revert it, for me worked like a charm.
`guest_os="windows-server"`

**Comment by jobukkit** [comment]
I also have this problem. When I try to install the driver from E:\ it just says the disk is inaccessible.

**Comment by marcoafo** [comment]
It seems that when download the virtio disk  the site is not protected by anubis, so instead of the ISO it's just the web page with the anti-bot challenge. Since a file is downloaded it's considered a ISO, then mounted. But win installer can't read it, so no virtio drivers are downloaded.

I tried to download the ISO manually and replace the ISO file. It boots but then Windows goes to error 0x40031. Maybe I downloaded the wrong virtio driver iso.

Just in case someone else wanna try: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/
