### ISSUE TITLE
bug: error while installng kali-weekly

### ISSUE THREAD

**Issue by EL3cKtr0** [quickemu-project/quickemu#930]
#### Expected behaviour

Installing kali-weekly with 'quickget kali weekly'

#### Actual behaviour

When i try to download kali-weekly with quickget, i receive an error I can fix with wget, but the URL is wrong (even with wget):
https://cdimage.kali.org/weekly/ -> https://cdimage.kali.org/kali-weekly/
Probably can do it without the wget simply fixing the 'get_kali' function setting the correct URL

#### Steps to reproduce the behaviour

quickget kali weekly

#### Quickemu output

[arch@arch]$ quickget kali weekly
kali-weekly/: Is a directory
ERROR! Failed to download https://cdimage.kali.org/weekly/ with wget. Try running 'quickget' again.

#### Linux Distribution & Kernel

Run the following and paste the output.

Arch Linux
6.7.4-arch1-1

**Comment by philclifford** [comment]
You need to request `kali-weekly`

```
$ quickget  kali 
ERROR! You must specify a release.
 - Releases: current kali-weekly

quickget -s kali kali-weekly
https://cdimage.kali.org/kali-weekly/kali-linux-2024-W06-installer-amd64.iso
```

**Comment by EL3cKtr0** [comment]
Thank you very much and sorry for the misunderstanding :D

**Comment by lj3954** [comment]
This still is an issue in the current release of quickget. Inputting only part of a valid OS, Release, or Edition name doesn't throw an error and list available values like it should; rather, it proceeds and either gives you a nonsensical error (e.g. "releases_win: command not found") or tries to download a file from a nonexistent URL. Quickget should test if the entire value matches. A simple way to do this would be to add spaces around the values being checked, since all of these values are separated by spaces.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickemu/pull/1097
