### ISSUE TITLE
MacOS Ventura get stuck at the final step of install

### ISSUE THREAD

**Issue by SnartFridge** [quickemu-project/quickemu#937]
#### Expected behaviour

MacOS Ventura to complete the final step of installation and be presented with an the out-of-the-box first-start wizard.

#### Actual behaviour

MacOS Ventura gets stuck on the _Less than a minute remaining..._ after the first reboot at installation. (I have left it for over 24 hours in case it just takes a while, and it does not finish)

#### Steps to reproduce the behaviour
I don't know how to reproduce it, I am hoping that the logs I copied help

#### Please read
I did see in the logs that running `sudo tee /sys/module/kvm/parameters/ignore_msrs` might solve the issue, but I did not do it because it said use it if you are unable to run macOS, and it was running great until this point? Would this parameter help? 
#### Quick emu output
```
Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.1
 - Host:     "EndeavourOS Linux" running Linux 6.(COMPUTER_NAME)
 - CPU:       Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permanent by running: 'quickemu --ignore-msrs-always'
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-ventura/disk.qcow2 (96G)
 - Display:  SDL, qxl-vga, GL (on), VirGL (off)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - 9P:       On guest: sudo mount_9p Public-smart___fridge
 - 9P:       On host:  chmod 777 /home/smart___fridge/Public
             Required for macOS integration 👆
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "macos-ventura/macos-ventura-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:macos-ventura/macos-ventura-monitor.socket
 - Serial:   On host:  nc -U "macos-ventura/macos-ventura-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:macos-ventura/macos-ventura-serial.socket
qemu-system-x86_64: -no-hpet: warning: -no-hpet is deprecated, use '-machine hpet=off' instead
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
 - Process:  Starting macos-ventura.conf as macos-ventura (6385)
```
#### Linux Distribution & Kernel
```
LSB Version:    n/a
Distributor ID: EndeavourOS
Description:    EndeavourOS Linux
Release:        rolling
Codename:       rolling
Linux COMPUTER_NAME 6.7.4-arch1-1.1-g14 #1 SMP PREEMPT_DYNAMIC Wed, 07 Feb 2024 13:01:49 +0000 x86_64 GNU/Linux
```

**Comment by SnartFridge** [comment]
Thanks for the response.
I followed the steps you provided, my CPU has avx2 capabilities, I updated the config file, and I changed the lines of code in quickemu. Hut something else is occurring during install that I don't know how to describe. I uploaded A video of quickemu running

Here is the link: https://youtu.be/FeFHRcG38-k

- During the first boot it promts me back to the boot menu
- During the second boot it freezes as seen
Is there anything I can do from here to fix the vm?

**Comment by TuxVinyards** [comment]
@SnartFridge  Pleased that you managed that and things installed.  I have a feeling that if you keep closing the VM and restarting, then something will eventually trigger.

However,  I was interested as to whether your problems were due to the 'old' macOS installer, the one that you are using, or whether you needed the new one that we are working on, or whether it was all down to needing to start and run the whole of the process with the tweaks that you have now installed ....

The Ventura VM that I had was built using the new, under-development, version.  So, this morning, in-between reading the news, I ran the old setup plus tweaks, as above and same as you.  

It did all the usual stuff, like take half an hour to do the 'less than a minute' section and generally just sit there with core monitors showing only idle status.   I went through all the usual stages, erase the main disk and install AppleFS, install the recovery image etc.

![ventura-tweaked-old-3](https://github.com/quickemu-project/quickemu/assets/3956806/ecc9ee8d-af0f-41d3-9d6d-b170f4eee864)

This was followed by an intermediary boot screen.   I should probably have made a snapshot of the main drive at this point but I pressed the 'base system' button  ...

![ventura-tweaked-old-5](https://github.com/quickemu-project/quickemu/assets/3956806/e875da69-8b85-433f-92c0-65deb09f5a76)

I seem to remember that this started the next installer phase, the longer one.  I may have restarted the VM?  But I was reading the news on my phone at the time  ....  

![ventura-tweaked-old-8-1min-start](https://github.com/quickemu-project/quickemu/assets/3956806/536b35c6-8bda-4120-a2ae-14bdf9589cc7)

After the forever 1 minute, I did make a couple of snapshots so I could easily return to a previous point in time again, using snapshot apply.

![ventura-tweaked-old-snapshot-1-min](https://github.com/quickemu-project/quickemu/assets/3956806/2eab5d22-7800-4d5e-afb2-3ec2c1761e9c)

I closed down, rebooted and got the same as in your video.  It chucked me off.   

A bit disappointedly,  I then closed the VM and restarted.  But this time something seemed to take and it all worked.  I went through the usual setup screens, refused all the telemetrics and Apple account invitations.  The mouse speed needed a speed tweak:

![ventura-tweaked-old-9](https://github.com/quickemu-project/quickemu/assets/3956806/33c4da3d-6889-4654-83f6-5457afcd6190)

See how, you get on.  You may get things to boot.  You may have to delete and retry from scratch.

Let us all know what happens. I am sure that others will want to give it a go too.  :rocket:

**Comment by SnartFridge** [comment]
Hello again, Sorry for the delay. I fell ill a few days ago, I did not get to fixing the VM.

I ended up deleting the old macOS VM and redownloaded it from scratch. The changes from before to Quickemu are still there.

After booting up the VM, it gets stuck immediately as seen:
![image](https://github.com/quickemu-project/quickemu/assets/123705853/18cafab5-445e-4bf1-b294-b175ba186b22)

I rebooted it a few times, and it seemed to end on different error messages:
![image](https://github.com/quickemu-project/quickemu/assets/123705853/1387b53a-4f4a-4408-b4d5-8ff5eba5c2d3)
![image](https://github.com/quickemu-project/quickemu/assets/123705853/35f33214-d5cf-46d2-925a-7db2e02c4af6)

Similar to the video I sent before, it sometimes boots and loops to the first screen but then after booting again, it freezes like the images above.

![image](https://github.com/quickemu-project/quickemu/assets/123705853/16c9e3ce-a7d1-4719-8bb0-4e1263c9e7d4)

**Comment by TuxVinyards** [comment]
Thank you for testing this all out.   You did fine with the code.  :+1: 

Now, what I want you to do is take another little leap of faith and install qqX.   I think your problems are due to using quickgui ....

The errors I am seeing appear to be saying about  vm_sharing.  This is probably due to quickgui using Spicy and smb,  which is probably the ntfs etc bit , I am guessing.  Your VM disk was formatted with APFS, no?   

Take the leap of faith, and then try loading up in SDL mode.  You can also try GTK as well to see what it is like.

See <https://github.com/quickemu-project/quickemu/issues/933>  

The other thing you can do before running, is to refresh your boot variables.  This is the qqX [rtv] option, in utils.

There are some other things to try.  But try qqX & SDL first, then get back to me.

**Comment by SnartFridge** [comment]
Sorry that I have not done anything for a while, I have fallen ill which has just drained my energy. I will get back to you tomorrow about the results of qqx and the vm

**Comment by TuxVinyards** [comment]
> Sorry that I have not done anything for a while, I have fallen ill which has just drained my energy. I will get back to you tomorrow about the results of qqx and the vm

Hope it's not my requests making you ill ...  Let me know if you are having problems.  Here to help.

**Comment by SnartFridge** [comment]
Hello, I am back. I am feeling better now, sorry about that. my entire family caught the flu. I recently discovered that there are a few corrupted file on my system that are causing issues across many applications. I am performing a full system reinstall and hopefully this helps the VM boot as well.

**Comment by fillumina** [comment]
I managed to make it work by simply repeating the same installation over and over. At the 4th or 5th tentative it finally completed.

**Comment by flexiondotorg** [comment]
Using Quickemu from the master (what will become 4.9.3) I have successfully installed Ventura.
